import os

SQLALCHEMY_DATABASE_URI = os.getenv('SQLALCHEMY_DATABASE_URI')
SQLALCHEMY_TRACK_MODIFICATIONS = False
MAIL_SERVER = os.getenv('MAIL_SERVER')
MAIL_PORT = os.getenv('MAIL_PORT')
MAIL_USERNAME = os.getenv('MAIL_USERNAME')
MAIL_PASSWORD = os.getenv('MAIL_PASSWORD')
MAIL_USE_SSL = os.getenv('MAIL_USE_SSL')
MAIL_DEFAULT_SENDER = os.getenv('MAIL_DEFAULT_SENDER')
SECRET_KEY = os.getenv('SECRET_KEY')
